apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dotnet-build-test
spec:
  entrypoint: build-and-test
  arguments:
    parameters:
      - name: repo-name
        value: ""
      - name: target-branch
        value: ""
  templates:
    - name: build-and-test
      steps:
        - - name: checkout-build-test
            template: checkout-build-test-template
    - name: checkout-build-test-template
      container:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        command: [sh, -c]
        args:
          - |
            git clone -b {{inputs.parameters.target-branch}} https://github.com/{{inputs.parameters.repo-name}} ./repos
            ls -a
            nuget locals all -clear
            dotnet restore "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            echo "Done restoring!"
            dotnet build "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            echo "Done building!"
            dotnet test "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            echo "Done testing!"