apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dotnet-build-test
spec:
  entrypoint: build-and-test
  templates:
    - name: build-and-test
      steps:
        - - name: install-dotnet
            template: install-dotnet-template
        - - name: checkout-build-test
            template: checkout-build-test-template
        - - name: checkout-dockerbuild-dockerpush
            template: checkout-dockerbuild-dockerpush-template
    - name: install-dotnet-template
      container:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        command: [sh, -c]
        args:
          - |
            echo "Installing .NET SDK"
            ls -a
            # Any further installation steps if needed.
    - name: checkout-build-test-template
      container:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        command: [sh, -c]
        args:
          - |
            git clone https://github.com/MaxBurgersSkyworkz/ContinuouslyRunningConsole.git ./repos
            ls -a
            nuget locals all -clear
            dotnet restore "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            echo "Done restoring!"
            dotnet build "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            echo "Done building!"
            dotnet test "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            echo "Done testing!"
      outputs:
        artifacts:
          - name: cloned-repo
            path: ./repos
    - name: checkout-dockerbuild-dockerpush-template
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=./repos/ContinuouslyRunningConsole/Dockerfile"
          - "--context=./repos/ContinuouslyRunningConsole"
          - "--destination=267074127319.dkr.ecr.eu-west-1.amazonaws.com/poc-wehkamp:latest"
        inputs:
          artifacts:
            - name: cloned-repo
              path: ./repos