apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dotnet-build-test
spec:
  entrypoint: build-and-test
  templates:
    - name: build-and-test
      steps:
        - - name: checkout-code
            container:
              image: alpine/git:latest
              command: [sh, -c]
              args:
                - |
                  git clone https://github.com/MaxBurgersSkyworkz/ContinuouslyRunningConsole.git .
                  dotnet restore
                  dotnet build
                  dotnet test