apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dotnet-build-test
spec:
  entrypoint: build-and-test
  templates:
    - name: build-and-test
      steps:
        - - name: checkout-and-build
            template: checkout-and-build-template
    - name: checkout-and-build-template
      container:
        image: mcr.microsoft.com/dotnet/sdk:8.0 # use same version as install
        command: [sh, -c]
        args:
          - |
            git clone https://github.com/MaxBurgersSkyworkz/ContinuouslyRunningConsole.git ./repos
            ls -a
            dotnet restore "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            dotnet build "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"
            dotnet test "./repos/ContinuouslyRunningConsole/ContinuouslyRunningConsole.csproj"