apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-push-sensor-template-trigger
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-push-dep
      eventSourceName: github-push
      eventName: push
  triggers:
    - template:
        name: argo-wf-template-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: git-template-triggered-
                namespace: argo
              spec:
                serviceAccountName: argo-platform-sa
                workflowTemplateRef:
                  name: main-workflow-template
                arguments:
                  parameters:
                    - name: repo-name
                    - name: target-branch
          parameters:
            - src:
                dependencyName: github-push-dep
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-push-dep
                dataKey: body.ref
              dest: spec.arguments.parameters.1.value